(("spacemacs" . ((user-emacs-directory . "~/.spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))))
 ("doom" . ((user-emacs-directory . "~/.doom")
            (env . (("DOOMDIR" . "~/.doom.d")))))
 )
